In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/loan_cleaned.csv")

print("Shape:", df.shape)

Shape: (1303638, 92)

Check target

In [3]:
print(df["default"].value_counts())

default
0    1041952
1     261686
Name: count, dtype: int64

In [ ]:
print(df["default"].value_counts(normalize=True) * 100)

Create credit-risk features

Feature 1 — Loan to Income

In [8]:
df["loan_to_income"] = (
    df["loan_amnt"] / (df["annual_inc"] + 1)
)

Feature 2 — Installment to Income

In [9]:
df["installment_to_income"] = (
    df["installment"] / (df["annual_inc"] + 1)
)

Feature 3 — Open Account Ratio

In [10]:
df["open_to_total_accounts"] = (
    df["open_acc"] / (df["total_acc"] + 1)
)

Feature 4 — Credit Issue Count

In [11]:
df["credit_issue_count"] = (
    df["delinq_2yrs"] + df["pub_rec"]
)

In [12]:
df["revol_bal_to_income"] = (
    df["revol_bal"] / (df["annual_inc"] + 1)
)

In [13]:
new_features = [
    "loan_to_income",
    "installment_to_income",
    "open_to_total_accounts",
    "credit_issue_count",
    "revol_bal_to_income"
]

df[new_features].describe().T

,count,mean,std,min,25%,50%,75%,max
loan_to_income,1303638.0,4.201286,303.902087,0.000171,0.124997,0.199995,0.290906,40000.000000
installment_to_income,1303638.0,0.123006,8.809086,0.000006,0.003865,0.006023,0.008790,1466.850000
open_to_total_accounts,1303638.0,0.474817,0.159695,0.000000,0.357143,0.461538,0.578947,1.555556
credit_issue_count,1303638.0,0.533144,1.054464,0.000000,0.000000,0.000000,1.000000,86.000000
revol_bal_to_income,1303638.0,3.508508,343.725561,0.000000,0.098499,0.179609,0.295599,181809.000000

In [14]:
df[new_features].isnull().sum()

loan_to_income            0
installment_to_income     0
open_to_total_accounts    0
credit_issue_count        0
revol_bal_to_income       0
dtype: int64

Check extreme values

In [15]:
df[new_features].quantile([0.01, 0.50, 0.99]).T

                            0.01      0.50      0.99
loan_to_income          0.025641  0.199995  0.499988
installment_to_income   0.000851  0.006023  0.016577
open_to_total_accounts  0.166667  0.461538  0.875000
credit_issue_count      0.000000  0.000000  5.000000
revol_bal_to_income     0.002610  0.179609  0.950808

In [16]:
X = df.drop(columns=["default"])
y = df["default"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (1303638, 92)
y shape: (1303638,)

In [17]:
print("Total features:", X.shape[1])

Total features: 92

In [18]:
df.to_csv(
    "../data/processed/loan_feature_engineered.csv",
    index=False
)